backend:
  name: git-gateway
  branch: main # Agar branch 'master' hai toh yahan master likhna

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Creative Gallery"
    folder: "images"
    create: true
    delete: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      
