backend:
  name: github
  repo: sahil-aditya/Creative_Gallery
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Website Content"
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      
