backend:
  name: git-gateway
  branch: main # Agar teri branch ka naam 'master' hai toh yahan master kar dena

media_folder: "images" # GitHub repo mein folder ka naam
public_folder: "/images" # Website par image ka path

collections:
  - name: "gallery"
    label: "Creative Gallery"
    folder: "images"
    create: true # Isse tu CMS se hi nayi images upload kar payega
    delete: true # Purani images delete karne ke liye
    extension: "jpg" # Default extension
    editor:
      preview: false
    fields:
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "File Name", name: "title", widget: "string", required: false}
      
