name: Generate Shop JSON

on:
  push:
    branches:
      - main
    paths:
      - 'Shop/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run script to generate shop.json
      run: |
        node generate-json.js # Path updated to the root directory

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add shop.json
        git commit -m "chore: Auto-generate shop.json" || true
        git push
