name: Sync Images from Google Drive

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug: List files before sync
        run: ls -lR

      - name: Sync files from Google Drive
        id: gdrive
        uses: gautamkrishnar/google-drive-upload@v1.3.1
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folder_id: 1XqT2oggvaYNpguTjBfjJMsUKzvYSyY5w
          destination: ./images
          command: download

      - name: Debug: List files after sync
        run: ls -lR

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: Sync images from Google Drive"
          git push
