name: Sync Images from Google Drive

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Google Drive CLI
        run: npm install -g google-drive-cli

      - name: Authenticate and Download Files
        env:
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          echo $GOOGLE_DRIVE_CREDENTIALS > credentials.json
          google-drive-cli sync --credentials credentials.json --folder-id 1XqT2oggvaYNpguTjBfjJMsUKzvYSyY5w --destination ./images

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Sync images from Google Drive" || true
          git push
          
