name: Update Images JSON

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate new images.json
        run: |
          # Create a temporary array for new images
          echo "[]" > new_images.json

          # Find all pairs of before/after images in the images folder
          ls images/ | sort | while read -r line
          do
            if [[ $line == *"_before."* ]]; then
              before_path="images/$line"
              after_path=$(echo "$line" | sed 's/_before/_after/')

              # Check if the "after" image exists
              if [ -f "$after_path" ]; then
                # Add the new pair to the temporary array
                jq '. += [{"before": "'"$before_path"'", "after": "'"$after_path"'"}]' new_images.json > tmp.json && mv tmp.json new_images.json
              fi
            fi
          done

          # Combine old and new image lists
          if [ -f images.json ]; then
            jq --slurp '.[0] + .[1]' images.json new_images.json > combined.json
            mv combined.json images.json
          else
            mv new_images.json images.json
          fi

          echo "Final images.json content:"
          cat images.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Check if the file images.json has been modified
          if [ -n "$(git status --porcelain images.json)" ]; then
            git add images.json
            git commit -m "chore: Auto-generated images.json"
            git push
          else
            echo "No changes to images.json. Skipping commit."
          fi
          
